[build]
  publish = "build" # Adjust if your build folder is named differently, like "dist"
  command = "npm run build" # Or "yarn build" if you're using Yarn

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
